project:
  type: website
  output-dir: docs

website:
  title: "Ed Merkle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
    right:
      - icon: mastodon
        href: https://mastodon.social/@edgarmerkle
      - icon: github
        href: https://github.com/ecmerkle

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



