project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!cs/msem.qmd"
    - "!cs/propodds.qmd"

website:
  title: "Ed Merkle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - text: Case Studies
        menu:
        - href: cs/ord_ic.qmd
          text: Ordinal likelihoods
        - href: cs/targets.qmd
          text: targets package
      - href: consult.qmd
        text: Consulting
    right:
      - icon: mastodon
        href: https://mastodon.sdf.org/@edgarmerkle
      - icon: bluesky
        href: https://bsky.app/profile/edgarmerkle.bsky.social
      - icon: github
        href: https://github.com/ecmerkle

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true

