---
title: "Publications"
---



Fife, D. A., Brunwasser, S., & Merkle, E. C. (in press). [Seeing the impossible: Visualizing latent variable models with *flexplavaan*](https://psyarxiv.com/qm7kj). *Psychological Methods*. (DOI: [10.1037/met0000468](https://doi.org/10.1037/met0000468)) 

Wiedermann, W., Frick, U., & Merkle, E. C. (in press). Detecting
heterogeneity of intervention effects in comparative judgments.
*Prevention Science*. (DOI:
[10.1007/s11121-021-01212-z](https://doi.org/10.1007/s11121-021-01212-z))

Flores, R. D., Sanders, C. A., Duan, S. X., Bishop-Chrzanowski, B. M., Oyler, D. L., Shim, H., Clocksin, H. E., Miller, A. P., & Merkle, E. C. (2022). [Before/After Bayes: A Comparison of Frequentist and Bayesian Mixed-Effects Models in Applied Psychological Research](https://osf.io/jz8nw). *British Journal of Psychology, 113*, 1164--1194. (DOI: [10.1111/bjop.12585](https://doi.org/10.1111/bjop.12585))

Wang, T., Graves, B., Rosseel, Y., & Merkle, E. C. (2022). [Computation and application of generalized linear mixed model derivatives using *lme4*](https://arxiv.org/abs/2011.10414). *Psychometrika, 87*, 1173--1193. (DOI: [10.1007/s11336-022-09840-2](https://doi.org/10.1007/s11336-022-09840-2))

Debelak, R., Pawel, S., Strobl, C., & Merkle, E. C. (2022). Score-based measurement invariance checks for Bayesian maximum-a-posteriori estimates in item response theory. *British Journal of Mathematical and Statistical Psychology, 75*, 728--752. (DOI: [10.1111/bmsp.12275](https://doi.org/10.1111/bmsp.12275))

Graves, B. & Merkle, E. C. (2022). [Identification constraints and fit indices in Bayesian latent variable models](https://osf.io/vxtdf/). *Behavior Research Methods, 54*, 795--804. (DOI: [10.3758/s13428-021-01649-8](https://doi.org/10.3758/s13428-021-01649-8))

Merkle, E. C., Fitzsimmons, E., Uanhoro, J., & Goodrich, B. (2021).
[Efficient Bayesian structural equation modeling in
Stan](https://doi.org/10.18637/jss.v100.i06). *Journal of Statistical
Software, 100*(6), 1--22.

Garnier-Villarreal, M., Merkle, E. C., & Magnus, B. E. (2021). Between-item multidimensional IRT: How far can the estimation methods go? *Psych, 3*, 404--421. (DOI: [10.3390/psych3030029](https://doi.org/10.3390/psych3030029))

Wang, T., Merkle, E. C., Anguera, J., & Turner B. M. (2021).
[Score-based tests for detecting heterogeneity in linear mixed
models](https://arxiv.org/abs/1901.05796). *Behavior Research Methods,
53*, 216--231. (DOI:
[10.3758/s13428-020-01375-7](https://doi.org/10.3758/s13428-020-01375-7))

### 2019--2020

Merkle, E. C., Saw, G., & Davis-Stober, C. (2020). [Beating the average
forecast: Regularization based on forecaster
attributes](https://osf.io/by93u/). *Journal of Mathematical Psychology,
98*, 102419. (DOI:
[10.1016/j.jmp.2020.102419](https://doi.org/10.1016/j.jmp.2020.102419))

Motschman, C. A., Hatz, L. E., McCarty, K. N., Merkle, E. C., Trull, T.
J., & McCarthy, D. M. (2020). Event-level predictors of alcohol-impaired
driving intentions. *Journal of Studies on Alcohol and Drugs, 81*(5),
647--654. (DOI:
[10.15288/jsad.2020.81.647](https://doi.org/10.15288/jsad.2020.81.647))

Haaf, J. M., Merkle, E. C., & Rouder, J. N. (2020). [Do items order? The
psychology in IRT models](https://psyarxiv.com/xsrfb/). *Journal of
Mathematical Psychology, 98*, 102398. (DOI:
[10.1016/j.jmp.2020.102398](https://doi.org/10.1016/j.jmp.2020.102398))

Scofield, J. E., Price, M. H., Flores, A., Merkle, E. C., & Johnson, J.
D. (2020). Repetition attenuates the influence of recency on recognition
memory: Behavioral and eletrophysiological evidence. *Psychophysiology,
57*, e13601. (DOI:
[10.1111/psyp.13601](http://dx.doi.org/10.1111/psyp.13601))

Schneider, L., Chalmers, R. P., Debelak, R., & Merkle, E. C. (2020).
[Model selection of nested and non-nested item response models using
Vuong tests](https://arxiv.org/abs/1810.04734). *Multivariate Behavioral
Research, 55*(5), 664--684. (DOI:
[10.1080/00273171.2019.1664280](https://doi.org/10.1080/00273171.2019.1664280))

Miller, A. P., Merkle, E. C., Galenkamp, H., Stronks, K., Derks, E. M.,
& Gizer, I. R. (2019). Differential item functioning analysis of the
CUDIT and relations with alcohol and tobacco use among men across five
ethnic groups: The HELIUS study. *Psychology of Addictive Behaviors,
33*(8), 697--709. (DOI:
[10.1037/adb0000521](http://dx.doi.org/10.1037/adb0000521))

Merkle, E. C., Furr, D., & Rabe-Hesketh, S. (2019). [Bayesian comparison
of latent variable models: Conditional versus marginal
likelihoods](https://arxiv.org/abs/1802.04452). *Psychometrika, 84*(3),
802--829. (DOI:
[10.1007/s11336-019-09679-0](http://dx.doi.org/10.1007/s11336-019-09679-0))

### 2017--2018

Wang, T., & Merkle, E. C. (2018). [Derivative computations and robust
standard errors for linear mixed effects models in
lme4](http://dx.doi.org/10.18637/jss.v087.c01). *Journal of Statistical
Software, 87*(c01), 1--16.

Merkle, E. C., & Rosseel, Y. (2018). [blavaan: Bayesian structural
equation models via parameter
expansion](https://doi.org/10.18637/jss.v085.i04). *Journal of
Statistical Software, 85*(4), 1--30.

Volpert-Esmond, H. I., Merkle, E. C., Levsen, M. P., Ito, T. A., &
Bartholow, B. D. (2018). Using trial-level data and multilevel modeling
to investigate within-task change in event-related potentials.
*Psychophysiology, 55*, e13044. (DOI:
[10.1111/psyp.13044](http://dx.doi.org/10.1111/psyp.13044))

Merkle, E. C., & Hartman, R. (2018). [Weighted Brier score
decompositions for topically heterogenous forecasting
tournaments](http://journal.sjdm.org/17/17614c/jdm17614c.pdf). *Judgment
and Decision Making, 13*, 185--201. ([Data and
code](https://osf.io/s5bne/))

Merkle, E. C., & Wang, T. (2018). [Bayesian latent variable models for
the analysis of experimental psychology
data](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2536989).
*Psychonomic Bulletin & Review*, *25*, 256--270. (DOI:
[10.3758/s13423-016-1016-7](http://dx.doi.org/10.3758/s13423-016-1016-7))

Wang, T., Strobl, C., Zeileis, A., & Merkle, E. C. (2018). [Score-based
tests of differential item functioning via pairwise maximum likelihood
estimation](https://eeecon.uibk.ac.at/~zeileis/papers/Wang+Strobl+Zeileis-2018.pdf).
*Psychometrika, 83*, 132--155. (DOI:
[10.1007/s11336-017-9591-8](http://dx.doi.org/10.1007/s11336-017-9591-8))

Wiedermann, W., Merkle, E. C., & von Eye, A. (2018). Direction of
dependence in measurement error models. *British Journal of Mathematical
and Statistical Psychology, 71*, 117--145. (DOI:
[10.1111/bmsp.12111](http://dx.doi.org/10.1111/bmsp.12111))

Volpert-Esmond, H. I., Merkle, E. C., & Bartholow, B. D. (2017). The
iterative nature of person construal: Evidence from event-related
potentials. *Social Cognitive and Affective Neuroscience, 12*,
1097--1107. (DOI:
[10.1093/scan/nsx048](http://dx.doi.org/10.1093/scan/nsx048))

Merkle, E. C., Steyvers, M., Mellers, B., & Tetlock, P. E. (2017). [A
neglected dimension of good forecasting judgment: The questions we
choose also
matter](pub/MerkleSteyversMellersTetlock2017.pdf).
*International Journal of Forecasting*, *33*, 817--832. (DOI:
[10.1016/j.ijforecast.2017.04.002](http://dx.doi.org/10.1016/j.ijforecast.2017.04.002))

Turner, B. M., Wang, T., & Merkle, E. C. (2017). [Factor analysis
linking functions for simultaneously modeling neural and behavioral
data](https://turnermbcn.files.wordpress.com/2017/08/turnerwangmerkle2017.pdf).
*NeuroImage*, *153*, 28--48. (DOI:
[10.1016/j.neuroimage.2017.03.044](http://dx.doi.org/10.1016/j.neuroimage.2017.03.044))

### 2015--2016

Merkle, E. C., You, D., & Preacher, K. J. (2016). [Testing non-nested
structural equation models](http://arxiv.org/pdf/1402.6720v3).
*Psychological Methods, 21*, 151-163. (DOI:
[10.1037/met0000038](http://dx.doi.org/10.1037/met0000038))

Merkle, E. C., Steyvers, M., Mellers, B., & Tetlock, P. E. (2016). [Item
response models of probability judgments: Application to a geopolitical
forecasting
tournament](pub/MerkleSteyversMellersTetlock2015.pdf).
*Decision*, *3*, 1--19. (DOI:
[10.1037/dec0000032](http://dx.doi.org/10.1037/dec0000032))

Merkle, E. (2016). [Discussion of the paper \"Of quantiles and
expectiles: Consistent scoring functions, Choquet representations and
forecast rankings\" by Ehm, Gneiting, Jordan, and
Kruger](https://doi.org/10.1111/rssb.12154). *Journal of the Royal
Statistical Society B, 78*, 550--551 (DOI:
[10.1111/rssb.12154](https://doi.org/10.1111/rssb.12154)).

Holmes-Rovner, M., Montgomery, J. S., Rovner, D. R., Scherer, L.,
Whitfield, J., Kahn, V. C., Merkle, E. C., Ubel, P. A., & Fagerlin, A.
(2015). Informed decision making: Assessment of the quality of physician
communication about prostate cancer diagnosis and treatment. *Medical
Decision Making*, *35*, 999--1009. (DOI:
[10.1177/0272989X15597226](http://dx.doi.org/10.1177/0272989X15597226))

Mellers, B., Stone, E., Atanasov, P., Rohrbaugh, N., Metz, S. E., Ungar,
L., Bishop, M., Horowitz, M., Merkle, E., & Tetlock, P. (2015). The
psychology of intelligence analysis: Drivers of prediction accuracy in
world politics. *Journal of Experimental Psychology: Applied*, *21*,
1--14. (DOI: [10.1037/xap0000040](http://dx.doi.org/10.1037/xap0000040))

### 2013--2014

Steyvers, M., Wallsten, T. S., Merkle, E. C., & Turner, B. M. (2014).
[Evaluating probabilistic forecasts with Bayesian signal detection
models](https://webfiles.uci.edu/msteyver/publications/Riskanalysis_SteyversWallstenMerkleTurner.pdf).
*Risk Analysis*, *34*, 435--452. (DOI:
[10.1111/risa.12127](http://dx.doi.org/10.1111/risa.12127))

Turner, B. M., Steyvers, M., Merkle, E. C., Budescu, D. V., & Wallsten,
T. S. (2014). [Forecast aggregation via
recalibration](https://webfiles.uci.edu/msteyver/publications/TurnerSteyversMerkleBudescuWallsten2014.pdf).
*Machine Learning*, *95*, 261--289. (DOI:
[10.1007/s10994-013-5401-4](http://dx.doi.org/10.1007/s10994-013-5401-4))

Wang, T., Merkle, E. C., & Zeileis, A. (2014). [Score-based tests of
measurement invariance: Use in
practice](http://journal.frontiersin.org/Journal/10.3389/fpsyg.2014.00438/abstract).
*Frontiers in Psychology*, *5 (438)*, 1--11.

Merkle, E. C., Fan, J., & Zeileis, A. (2014). [Testing for measurement
invariance with respect to an ordinal
variable](pub/MerkleFanZeileis2014.pdf).
*Psychometrika*, *79*, 569--584. (DOI:
[10.1007/s11336-013-9376-7](http://dx.doi.org/10.1007/s11336-013-9376-7))

Merkle, E. C., & Steyvers, M. (2013). [Choosing a strictly proper
scoring
rule](pub/MerkleSteyvers2013.pdf).
*Decision Analysis*, *10*, 292--304. (DOI:
[10.1287/deca.2013.0280](http://dx.doi.org/10.1287/deca.2013.0280))

Merkle, E. C., & Zeileis, A. (2013). [Tests of measurement invariance
without subgroups: A generalization of classical
methods](pub/MerkleZeileis2013.pdf).
*Psychometrika*, *78*, 59--82. (DOI:
[10.1007/s11336-012-9302-4](http://dx.doi.org/10.1007/s11336-012-9302-4))

Shaffer, V. A., Probst, C. A., Merkle, E. C., Arkes, H. R., & Medow, M.
A. (2013). Why do patients derogate physicians who use a computer-based
diagnostic support system? *Medical Decision Making, 33*, 108-118. (DOI:
[10.1177/0272989X12453501](http://dx.doi.org/10.1177/0272989X12453501))

### 2011--2012

Shaffer, V. A., Merkle, E. C., Fagerlin, A., Griggs, J. J., Langa, K.
M., & Iwashyna, T. J. (2012). Chemotherapy was not associated with
cognitive decline in older adults with breast and colorectal cancer:
Findings from a prospective cohort study. *Medical Care*, *50*,
849--855. (DOI:
[10.1097/MLR.0b013e31825a8bb0](http://dx.doi.org/10.1097/MLR.0b013e31825a8bb0))

Warnaar, D. B., Merkle, E. C., Steyvers, M., Wallsten, T. S., Stone, E.
R., Budescu, D. V., Yates, J. F., Sieck, W. R., Arkes, H. R., Argenta,
C. F., Shin, Y., & Carter, J. N. (2012). [The aggregative contingent
estimation system: Selecting, rewarding, and training experts in a
wisdom of crowds approach to
forecasting](http://www.aaai.org/ocs/index.php/SSS/SSS12/paper/view/4290).
In *Proceedings of the 2012 Association for the Advancement of
Artificial Intelligence Spring Symposium Series (AAAI Technical Report
SS-12-06)* (pp. 75--76).

Preacher, K. J., & Merkle, E. C. (2012). [The problem of model selection
uncertainty in structural equation
modeling](http://quantpsy.org/pubs/preacher_merkle_2012.pdf).
*Psychological Methods*, *17*, 1--14. (DOI:
[10.1037/a0026804](http://dx.doi.org/10.1037/a0026804))

Merkle, E. C. (2011). [A comparison of imputation methods for Bayesian
factor analysis
models](pub/Merkle2011.pdf).
*Journal of Educational and Behavioral Statistics*, *36*, 257--276.
(DOI:
[10.3102/1076998610375833](http://dx.doi.org/10.3102/1076998610375833))

Merkle, E. C., & Steyvers, M. (2011). [A psychological model for
aggregating judgments of
magnitude](https://webfiles.uci.edu/msteyver/publications/MerkleSteyvers2011.pdf).
In J. Salerno, S. J. Yang, D. Nau, & S.-K. Chai (eds.), *Social
computing and behavioral-cultural modeling 2011* (pp. 236--243). Lecture
Notes in Computer Science 6589.

Smithson, M., Merkle, E. C., & Verkuilen, J. (2011). Beta regression
finite mixture models of polarization and priming. *Journal of
Educational and Behavioral Statistics*, *36*, 804--831. (DOI:
[10.3102/1076998610396893](http://dx.doi.org/10.3102/1076998610396893))

Merkle, E. C., & Shaffer, V. A. (2011). [Binary recursive partitioning:
Background, methods, and application to
psychology](pub/MerkleShaffer2011.pdf).
*British Journal of Mathematical and Statistical Psychology*, *64*,
161--181. (DOI:
[10.1348/000711010X503129](http://dx.doi.org/10.1348/000711010X503129))

Merkle, E. C., Smithson, M., & Verkuilen, J. (2011). [Hierarchical
models of simple mechanisms underlying confidence in decision
making](pub/MerkleSmithsonVerkuilen2011.pdf).
*Journal of Mathematical Psychology*, *55*, 57--67. (DOI:
[10.1016/j.jmp.2010.08.011](http://dx.doi.org/10.1016/j.jmp.2010.08.011))

### Pre-2011

Merkle, E. C. (2010). [Calibrating subjective probabilities using
hierarchical Bayesian
models](pub/Merkle2010.pdf). In
S.-K. Chai, J. J. Salerno, & P. L. Mabry (eds.), *Social computing,
behavioral modeling, and prediction (SBP) 2010* (pp. 13--22).
Heidelberg: Springer.

Merkle, E. C. (2009). [The disutility of the hard-easy effect in choice
confidence](pub/Merkle2009.pdf).
*Psychonomic Bulletin and Review*, *16*, 204--213. (DOI:
[10.3758/PBR.16.1.204](http://dx.doi.org/10.3758/PBR.16.1.204))

Merkle, E. C., Sieck, W. R., & Van Zandt, T. (2008). [Response error and
processing biases in confidence
judgment](http://www.globalcognition.org/wp-content/uploads/2012/03/merkle-jbdm08v21p428-ErrorVsBias.pdf).
*Journal of Behavioral Decision Making*, *21*, 428--448. (DOI:
[10.1002/bdm.597](http://dx.doi.org/10.1002/bdm.597))

Merkle, E. C., Van Zandt, T., & Sieck, W. R. (2008). [Rejoinder: Error
in confidence
judgments](pub/MerkleVanZandtSieck2008.pdf).
*Journal of Behavioral Decision Making*, *21*, 453--456. (DOI:
[10.1002/bdm.605](http://dx.doi.org/10.1002/bdm.605))

Brown, L. D., Shepherd, M. D., Merkle, E. C., Wituk, S. A., & Meissen,
G. (2008). Understanding how participation in a consumer-run
organization relates to recovery. *American Journal of Community
Psychology, 42*, 167-178. *American Journal of Community Psychology*,
*42*, 167--178. (DOI:
[10.1007/s10464-008-9184-x](http://dx.doi.org/10.1007/s10464-008-9184-x))

Sieck, W. R., Merkle, E. C., & Van Zandt, T. (2007). [Option fixation: A
cognitive contributor to
overconfidence](http://www.globalcognition.org/wp-content/uploads/2012/03/sieck-obhdp07v103p68-OptionFixation.pdf).
*Organizational Behavior and Human Decision Processes*, *103*, 68--83.
(DOI:
[10.1016/j.obhdp.2006.11.001](http://dx.doi.org/10.1016/j.obhdp.2006.11.001))

Merkle, E. C., & Van Zandt, T. (2006). An application of the Poisson
race model to confidence calibration. *Journal of Experimental
Psychology: General*, *135*, 391--408. (DOI:
[10.1037/0096-3445.135.3.391](http://dx.doi.org/10.1037/0096-3445.135.3.391))
